"""
Retrieves topics and words using LDA and writes them to a file
"""

from gensim.corpora import Dictionary, MmCorpus
from gensim.models.ldamodel import LdaModel

# removes symbols given a text input
symbols = [',', '.', '-', '@']
def clean(word):
    word = word.lower()
    for symbol in symbols:
        word = word.replace(symbol, '')
    return word

# load dictionary that was generated by calling corpora.Dictionary() on TripAdvisor text
id2word = Dictionary.load('scraper/tripadvisor.dict')
# constructs a sparse matrix by calling corpora.MmCorpus.serialize() on the dictionary
mm = MmCorpus('scraper/tripadvisor.mm')
# call LDA, set topics to 100
lda = LdaModel(corpus=mm, id2word=id2word, num_topics=100, update_every=1, chunksize=100, passes=1)
topics = lda.print_topics(num_topics=100)

top_words = []

# construct top words list based on topics and words generated by LDA
for topic in topics:
    topic = topic.replace('+', '')
    topic_split = topic.split()
    for item in topic_split:
        item = item.strip().split('*')[1]
        top_words.append(clean(item))

# write top words to a file
f = open('scraper/top_words_lda.txt', 'w')
for word in top_words:
    f.write(word.encode('utf-8') + '\n')
f.close()